# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49887e650631b67696eb4927daa59461d454dfbc34eefac5442bc7ca05193e627ab29bf66c7e83e00ad351cccfa7024979659d83fddd0b4eb830821da9ddab09

test:
  secret_key_base: fb3b3da59aa65feeca942e01379c8807ca8509371e658f4cad5d35ee602ff6a689b3dc01f34b98175a9a241c444489d801d0cd942c93ff4c55090f81c023a426

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
